classdef color_lee
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here

    properties
        gradient = struct(red = [],...
            green = [],...
            blue = [],...
            magenta = [],...
            cyan = [],...
            yellow = [],...
            gray = [],...
            inferno = [])
    end

    properties (Constant)
        clist = struct(...
            'white', [1,1,1],...
            'black', [0,0,0],...
            'cyan', [0,1,1],...
            'magenta', [1,0,1],...
            'yellow', [1,1,0],...
            'red', [1,0,0],...
            'green', [0,1,0],...
            'blue', [0,0,1],...
            'orange', [1,0.5,0],...
            'lightgreen', [0.4,0.8,0.4],...
            'darkgreen', [0,0.5,0],...
            'coloredorange', [1,0.7,0],...
            'coloredgreen', [0.6,1,0],...
            'purple', [0.5, 0, 0.5],...
            'teal', [0, 0.5, 0.5],...
            'gray', [0.5, 0.5, 0.5],...
            'lightgray', [0.8, 0.8, 0.8],...
            'darkgray', [0.2, 0.2, 0.2],...
            'brown', [0.6, 0.3, 0.1],...
            'pink', [1, 0.75, 0.8],...
            'gold', [1, 0.84, 0],...
            'navy', [0, 0, 0.5],...
            'maroon', [0.5, 0, 0]);
    end

    methods
        function obj = color_lee()
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
            obj.gradient.red =    [linspace(0,1,256)', zeros(256,1), zeros(256,1)];
            obj.gradient.green =    [zeros(256,1), linspace(0,1,256)', zeros(256,1)];
            obj.gradient.blue =    [zeros(256,1), zeros(256,1), linspace(0,1,256)'];
            obj.gradient.magenta =    [linspace(0,1,256)', zeros(256,1), linspace(0,1,256)'];
            obj.gradient.cyan =    [zeros(256,1),linspace(0,1,256)', linspace(0,1,256)'];
            obj.gradient.yellow =    [linspace(0,1,256)', linspace(0,1,256)',zeros(256,1)];
            obj.gradient.gray =    [linspace(0,1,256)', linspace(0,1,256)', linspace(0,1,256)'];

            % Inferno approximation
            x = [0, 0.15, 0.3, 0.5, 0.75, 1];
            r = [0, 0.1, 0.3, 0.7, 0.95, 1];
            g = [0, 0, 0.05, 0.2, 0.6, 1];
            b = [0, 0.2, 0.4, 0.1, 0.1, 0.8];
            points = linspace(0,1,256);
            obj.gradient.inferno = [interp1(x,r,points,'pchip')', interp1(x,g,points,'pchip')', interp1(x,b,points,'pchip')'];
            obj.gradient.inferno = max(0, min(1, obj.gradient.inferno));
        end
    end
end

