classdef color_lee
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        gradient = struct(red = [],...
        green = [],...
        blue = [],...
        magenta = [],...
        cyan = [],...
        yellow = [],...
        gray = [])
    end
    
    properties (Constant)
        clist = struct(...
        'white', [1,1,1],...
        'black', [0,0,0],...
        'cyan', [0,1,1],...
        'magenta', [1,0,1],...
        'yellow', [1,1,0],...
        'red', [1,0,0],...
        'green', [0,1,0],...
        'blue', [0,0,1],...
        'orange', [1,0.5,0],...
        'lightgreen', [0.4,0.8,0.4],...
        'darkgreen', [0,0.5,0]);
    end

    methods
        function obj = color_lee()
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
            obj.gradient.red =    [linspace(0,1,256)', zeros(256,1), zeros(256,1)];
            obj.gradient.green =    [zeros(256,1), linspace(0,1,256)', zeros(256,1)];
            obj.gradient.blue =    [zeros(256,1), zeros(256,1), linspace(0,1,256)'];
            obj.gradient.magenta =    [linspace(0,1,256)', zeros(256,1), linspace(0,1,256)'];
            obj.gradient.cyan =    [zeros(256,1),linspace(0,1,256)', linspace(0,1,256)'];
            obj.gradient.yellow =    [linspace(0,1,256)', linspace(0,1,256)',zeros(256,1)];
            obj.gradient.gray =    [linspace(0,1,256)', linspace(0,1,256)', linspace(0,1,256)'];
        end
    end
end

